# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Prometheos TP-Link exporter
version: "1.0.1-b3"
slug: prometheos-tplink-exporter
description: "Prometheos exporter for TP-Link smart devices"
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  switch_ip: "192.168.2.1"
  username: "admin"
  password: "admin"

schema:
  switch_ip: str
  username: str
  password: password

environment:
  SWITCH_IP: "!env switch_ip"
  USERNAME: "!env username"
  PASSWORD: "!env password"
