name: TL-SG Prometheus Exporter
slug: tl_sg_exporter
description: Prometheus exporter for TP-Link TL-SG Easy Smart switches
version: "1.0.0"
startup: services
boot: auto
init: false

arch:
  - amd64
  - aarch64
  - armv7

ports:
  9108/tcp: 9108

options:
  switch_ip: "192.168.2.1"
  username: "admin"
  password: "admin"

schema:
  switch_ip: str
  username: str
  password: password

environment:
  SWITCH_IP: "!env switch_ip"
  USERNAME: "!env username"
  PASSWORD: "!env password"

panel_icon: mdi:lan
